### ISSUE TITLE
家人们啊，我卡在第一步了poetry install RuntimeError

### ISSUE THREAD

**Issue by Xiaojack1026** [Mar-7th/March7th#11]
![image](https://github.com/Mar-7th/March7th/assets/125620242/4b38a44f-4b80-413d-998c-075601f8fe96)

**Comment by Xiaojack1026** [comment]
升级版本后OK了，现在又在这nb run这里了，他说
nonebot没有安装
root@waqn-virtual:/home/wan/文档/March7th/March7th# nb run
Traceback (most recent call last):
  File "/root/.local/bin/nb", line 8, in <module>
    sys.exit(main())
  File "/root/.local/pipx/venvs/nb-cli/lib/python3.10/site-packages/nb_cli/__main__.py", line 10, in main
    anyio.run(cli_main, *args)
  File "/root/.local/pipx/venvs/nb-cli/lib/python3.10/site-packages/anyio/_core/_eventloop.py", line 70, in run
    return asynclib.run(func, *args, **backend_options)
  File "/root/.local/pipx/venvs/nb-cli/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 292, in run
    return native_run(wrapper(), debug=debug)
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/root/.local/pipx/venvs/nb-cli/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 287, in wrapper
    return await func(*args)
  File "/root/.local/pipx/venvs/nb-cli/lib/python3.10/site-packages/nb_cli/__init__.py", line 35, in cli_main
    return await run_sync(cli_sync)(*args, **kwargs)
  File "/root/.local/pipx/venvs/nb-cli/lib/python3.10/site-packages/nb_cli/cli/utils.py", line 61, in wrapper
    return await anyio.to_thread.run_sync(partial(func, *args, **kwargs))
  File "/root/.local/pipx/venvs/nb-cli/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/root/.local/pipx/venvs/nb-cli/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/root/.local/pipx/venvs/nb-cli/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/root/.local/pipx/venvs/nb-cli/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/root/.local/pipx/venvs/nb-cli/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/root/.local/pipx/venvs/nb-cli/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/.local/pipx/venvs/nb-cli/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/.local/pipx/venvs/nb-cli/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/root/.local/pipx/venvs/nb-cli/lib/python3.10/site-packages/nb_cli/cli/utils.py", line 69, in wrapper
    return anyio.from_thread.run(partial(func, *args, **kwargs))
  File "/root/.local/pipx/venvs/nb-cli/lib/python3.10/site-packages/anyio/from_thread.py", line 49, in run
    return asynclib.run_async_from_thread(func, *args)
  File "/root/.local/pipx/venvs/nb-cli/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 970, in run_async_from_thread
    return f.result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 458, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/root/.local/pipx/venvs/nb-cli/lib/python3.10/site-packages/nb_cli/cli/commands/project.py", line 349, in run
    proc = await run_project(
  File "/root/.local/pipx/venvs/nb-cli/lib/python3.10/site-packages/nb_cli/handlers/meta.py", line 118, in wrapper
    return await func(*args, **kwargs)
  File "/root/.local/pipx/venvs/nb-cli/lib/python3.10/site-packages/nb_cli/handlers/meta.py", line 163, in wrapper
    raise NoneBotNotInstalledError(_("NoneBot is not installed."))
nb_cli.exceptions.NoneBotNotInstalledError: NoneBot 未安装.

**Comment by mobyw** [comment]
```bash
poetry install
poetry run nb run
```

**Comment by mobyw** [comment]
或者设置 `poetry` 虚拟环境目录为当前文件夹下的 `.venv`

**Comment by Xiaojack1026** [comment]
我又来麻烦大佬了gocqhttp不能加载了
root@waqn-virtual:/home/wan/文档/March7th/March7th# poetry run nb run
06-09 13:53:49 [SUCCESS] nonebot | NoneBot is initializing...
06-09 13:53:49 [INFO] nonebot | Current Env: prod
06-09 13:53:50 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_saa"
06-09 13:53:50 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_localstore"
06-09 13:53:50 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_datastore"
06-09 13:53:50 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_srres" from "march7th.nonebot_plugin_srres"
06-09 13:53:50 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_srhelp" from "march7th.nonebot_plugin_srhelp"
06-09 13:53:50 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_apscheduler"
06-09 13:53:51 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_mys_api" from "march7th.nonebot_plugin_mys_api"
06-09 13:53:51 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_srbind" from "march7th.nonebot_plugin_srbind"
06-09 13:53:51 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_srinfo" from "march7th.nonebot_plugin_srinfo"
06-09 13:53:51 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_srpanel" from "march7th.nonebot_plugin_srpanel"
06-09 13:53:51 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_srwiki" from "march7th.nonebot_plugin_srwiki"
06-09 13:53:51 [ERROR] nonebot | Failed to import "nonebot_plugin_gocqhttp"
Traceback (most recent call last):
  File "<string>", line 16, in <module>
  File "/root/.cache/pypoetry/virtualenvs/march7th-TK-MTFo0-py3.10/lib/python3.10/site-packages/nonebot/plugin/load.py", line 125, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "/root/.cache/pypoetry/virtualenvs/march7th-TK-MTFo0-py3.10/lib/python3.10/site-packages/nonebot/plugin/load.py", line 62, in load_all_plugins
    return manager.load_all_plugins()
  File "/root/.cache/pypoetry/virtualenvs/march7th-TK-MTFo0-py3.10/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 175, in load_all_plugins
    return set(
  File "/root/.cache/pypoetry/virtualenvs/march7th-TK-MTFo0-py3.10/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 176, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "/root/.cache/pypoetry/virtualenvs/march7th-TK-MTFo0-py3.10/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 141, in load_plugin
    module = importlib.import_module(name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'nonebot_plugin_gocqhttp'
06-09 13:53:51 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_mys_api" from "march7th.nonebot_plugin_mys_api"
06-09 13:53:51 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_srcode" from "march7th.nonebot_plugin_srcode"
06-09 13:53:51 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_srmemo" from "march7th.nonebot_plugin_srmemo"
06-09 13:53:51 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_srres" from "march7th.nonebot_plugin_srres"
06-09 13:53:51 [SUCCESS] nonebot | Running NoneBot...
06-09 13:53:51 [INFO] uvicorn | Started server process [4062]
06-09 13:53:51 [INFO] uvicorn | Waiting for application startup.
06-09 13:53:51 [INFO] nonebot_plugin_datastore | 数据库初始化完成
06-09 13:53:51 [INFO] nonebot_plugin_srres | 正在检查索引文件是否完整
06-09 13:53:51 [INFO] nonebot_plugin_srres | 索引文件检查完毕
06-09 13:53:51 [INFO] nonebot_plugin_srres | 正在检查字体文件是否完整
06-09 13:53:51 [INFO] nonebot_plugin_srres | 字体文件检查完毕
06-09 13:53:51 [INFO] nonebot_plugin_srres | 『崩坏：星穹铁道』游戏资源列表加载完成
06-09 13:53:51 [INFO] nonebot_plugin_apscheduler | Scheduler Started
06-09 13:53:51 [INFO] nonebot_plugin_mys_api | Device id & fp refreshed
06-09 13:53:51 [INFO] uvicorn | Application startup complete.
06-09 13:53:51 [INFO] uvicorn | Uvicorn running on http://0.0.0.0:23037 (Press CTRL+C to quit)
06-09 13:56:01 [INFO] uvicorn | 127.0.0.1:53270 - "GET / HTTP/1.1" 404

**Comment by mobyw** [comment]
先安装

```bash
poetry run nb plugin install nonebot_plugin_gocqhttp
```

**Comment by Xiaojack1026** [comment]
大佬好，更新面板失败，其他都ok
06-09 14:37:13 [INFO] nonebot_plugin_srpanel | 正在更新SRUID『106031717』角色面板
06-09 14:37:13 [INFO] nonebot_plugin_gocqhttp | [172822512] 发送好友 272962496(272962496)  的消息: [{"type":  ... (-1169421671)
06-09 14:37:15 [INFO] nonebot_plugin_srpanel | Can not parse: {'detailInfo': {'worldLevel': 4, 'platform': 'ANDROID', 'friendCount': 6, 'signature': '出UP，立马氪，不出不氪，大保底不氪，契约已成', 'isDisplayAvatar': True, 'avatarDetailList': [{'avatarId': 8003, 'promotion': 5, 'skillTreeList': [{'pointId': 8003001, 'level': 4}, {'pointId': 8003002, 'level': 6}, {'pointId': 8003003, 'level': 6}, {'pointId': 8003004, 'level': 6}, {'pointId': 8003007, 'level': 1}, {'pointId': 8003101, 'level': 1}, {'pointId': 8003102, 'level': 1}, {'pointId': 8003201, 'level': 1}, {'pointId': 8003202, 'level': 1}, {'pointId': 8003203, 'level': 1}, {'pointId': 8003204, 'level': 1}, {'pointId': 8003205, 'level': 1}], 'relicList': [{'type': 1, 'tid': 61031, 'subAffixList': [{'affixId': 2, 'cnt': 1}, {'affixId': 4, 'cnt': 3, 'step': 2}, {'affixId': 5, 'cnt': 2, 'step': 1}, {'affixId': 11, 'cnt': 2, 'step': 1}], 'level': 15, 'mainAffixId': 1}, {'exp': 9220, 'type': 2, 'tid': 61032, 'subAffixList': [{'affixId': 1, 'cnt': 1, 'step': 2}, {'affixId': 3, 'cnt': 1}, {'affixId': 6, 'cnt': 3, 'step': 4}, {'affixId': 7, 'cnt': 2, 'step': 2}], 'level': 14, 'mainAffixId': 1}, {'type': 3, 'tid': 55004, 'subAffixList': [{'affixId': 2, 'cnt': 2, 'step': 3}, {'affixId': 4, 'cnt': 1, 'step': 1}, {'affixId': 5, 'cnt': 1, 'step': 1}, {'affixId': 11, 'cnt': 1}], 'level': 6, 'mainAffixId': 1}, {'type': 4, 'tid': 61034, 'subAffixList': [{'affixId': 2, 'cnt': 1}, {'affixId': 5, 'cnt': 2, 'step': 1}, {'affixId': 9, 'cnt': 2, 'step': 3}, {'affixId': 11, 'cnt': 3, 'step': 3}], 'level': 15, 'mainAffixId': 3}, {'type': 5, 'tid': 53075, 'subAffixList': [{'affixId': 2, 'cnt': 1, 'step': 2}, {'affixId': 8, 'cnt': 1}, {'affixId': 10, 'cnt': 2, 'step': 1}, {'affixId': 12, 'cnt': 1}], 'level': 6, 'mainAffixId': 3}, {'type': 6, 'tid': 53076, 'subAffixList': [{'affixId': 1, 'cnt': 1, 'step': 1}, {'affixId': 2, 'cnt': 1, 'step': 1}, {'affixId': 10, 'cnt': 1}, {'affixId': 12, 'cnt': 1, 'step': 2}], 'level': 6, 'mainAffixId': 5}], 'equipment': {'level': 70, 'tid': 23005, 'promotion': 5, 'rank': 1}, 'rank': 4, 'exp': 14120, 'level': 69}, {'pos': 1, 'avatarId': 1204, 'promotion': 5, 'skillTreeList': [{'pointId': 1204001, 'level': 4}, {'pointId': 1204002, 'level': 6}, {'pointId': 1204003, 'level': 6}, {'pointId': 1204004, 'level': 6}, {'pointId': 1204007, 'level': 1}, {'pointId': 1204101, 'level': 1}, {'pointId': 1204102, 'level': 1}, {'pointId': 1204201, 'level': 1}, {'pointId': 1204202, 'level': 1}, {'pointId': 1204203, 'level': 1}, {'pointId': 1204204, 'level': 1}, {'pointId': 1204205, 'level': 1}], 'relicList': [{'type': 1, 'tid': 51111, 'subAffixList': [{'affixId': 5, 'cnt': 1, 'step': 1}, {'affixId': 7, 'cnt': 1}, {'affixId': 9, 'cnt': 1, 'step': 2}, {'affixId': 10, 'cnt': 2, 'step': 1}], 'level': 9, 'mainAffixId': 1}, {'type': 2, 'tid': 61112, 'subAffixList': [{'affixId': 1, 'cnt': 1, 'step': 2}, {'affixId': 6, 'cnt': 2, 'step': 4}, {'affixId': 8, 'cnt': 1, 'step': 2}, {'affixId': 10, 'cnt': 4, 'step': 4}], 'level': 15, 'mainAffixId': 1}, {'type': 3, 'tid': 51113, 'subAffixList': [{'affixId': 2, 'cnt': 1, 'step': 1}, {'affixId': 3, 'cnt': 1}, {'affixId': 4, 'cnt': 1, 'step': 1}, {'affixId': 6, 'cnt': 2, 'step': 2}], 'level': 6, 'mainAffixId': 4}, {'type': 4, 'tid': 51114, 'subAffixList': [{'affixId': 2, 'cnt': 1, 'step': 1}, {'affixId': 3, 'cnt': 1}, {'affixId': 4, 'cnt': 1, 'step': 2}, {'affixId': 5, 'cnt': 1, 'step': 1}], 'level': 6, 'mainAffixId': 4}, {'type': 5, 'tid': 53055, 'subAffixList': [{'affixId': 1, 'cnt': 1, 'step': 2}, {'affixId': 5, 'cnt': 1, 'step': 1}], 'mainAffixId': 7}, {'exp': 240, 'type': 6, 'tid': 63056, 'subAffixList': [{'affixId': 1, 'cnt': 1, 'step': 1}, {'affixId': 2, 'cnt': 1, 'step': 1}, {'affixId': 10, 'cnt': 1, 'step': 1}], 'level': 2, 'mainAffixId': 1}], 'equipment': {'level': 70, 'tid': 21027, 'promotion': 5, 'rank': 3}, 'exp': 18082, 'level': 69}, {'pos': 2, 'avatarId': 1102, 'promotion': 5, 'skillTreeList': [{'pointId': 1102001, 'level': 4}, {'pointId': 1102002, 'level': 7}, {'pointId': 1102003, 'level': 7}, {'pointId': 1102004, 'level': 7}, {'pointId': 1102007, 'level': 1}, {'pointId': 1102101, 'level': 1}, {'pointId': 1102102, 'level': 1}, {'pointId': 1102201, 'level': 1}, {'pointId': 1102202, 'level': 1}, {'pointId': 1102203, 'level': 1}, {'pointId': 1102204, 'level': 1}, {'pointId': 1102205, 'level': 1}], 'relicList': [{'exp': 200, 'type': 1, 'tid': 51081, 'subAffixList': [{'affixId': 3, 'cnt': 1, 'step': 2}, {'affixId': 4, 'cnt': 1, 'step': 2}, {'affixId': 8, 'cnt': 2, 'step': 3}, {'affixId': 12, 'cnt': 1}], 'level': 9, 'mainAffixId': 1}, {'type': 2, 'tid': 61082, 'subAffixList': [{'affixId': 1, 'cnt': 2}, {'affixId': 3, 'cnt': 2, 'step': 1}, {'affixId': 8, 'cnt': 2, 'step': 3}, {'affixId': 9, 'cnt': 2, 'step': 1}], 'level': 15, 'mainAffixId': 1}, {'type': 3, 'tid': 51083, 'subAffixList': [{'affixId': 1, 'cnt': 1, 'step': 2}, {'affixId': 2, 'cnt': 2, 'step': 2}, {'affixId': 3, 'cnt': 1, 'step': 1}, {'affixId': 11, 'cnt': 1, 'step': 1}], 'level': 9, 'mainAffixId': 3}, {'type': 4, 'tid': 61084, 'subAffixList': [{'affixId': 4, 'cnt': 3, 'step': 4}, {'affixId': 6, 'cnt': 1, 'step': 2}, {'affixId': 10, 'cnt': 2, 'step': 1}, {'affixId': 11, 'cnt': 2, 'step': 2}], 'level': 15, 'mainAffixId': 2}, {'type': 5, 'tid': 53065, 'subAffixList': [{'affixId': 2, 'cnt': 1, 'step': 1}, {'affixId': 3, 'cnt': 1, 'step': 2}], 'mainAffixId': 9}, {'type': 6, 'tid': 63066, 'subAffixList': [{'affixId': 2, 'cnt': 1, 'step': 1}, {'affixId': 4, 'cnt': 1, 'step': 1}, {'affixId': 12, 'cnt': 1, 'step': 1}], 'mainAffixId': 4}], 'equipment': {'level': 70, 'tid': 24001, 'promotion': 5, 'rank': 5}, 'exp': 39174, 'level': 69}], 'recordInfo': {'achievementCount': 176, 'challengeInfo': {'scheduleMaxLevel': 10}, 'equipmentCount': 26, 'maxRogueChallengeScore': 6, 'avatarCount': 16}, 'headIcon': 201001, 'nickname': '保底人不吃牛杂', 'assistAvatarDetail': {'avatarId': 1211, 'promotion': 5, 'skillTreeList': [{'pointId': 1211001, 'level': 4}, {'pointId': 1211002, 'level': 6}, {'pointId': 1211003, 'level': 8}, {'pointId': 1211004, 'level': 6}, {'pointId': 1211007, 'level': 1}, {'pointId': 1211101, 'level': 1}, {'pointId': 1211102, 'level': 1}, {'pointId': 1211201, 'level': 1}, {'pointId': 1211202, 'level': 1}, {'pointId': 1211203, 'level': 1}, {'pointId': 1211204, 'level': 1}, {'pointId': 1211205, 'level': 1}], 'relicList': [{'exp': 2220, 'type': 1, 'tid': 61011, 'subAffixList': [{'affixId': 2, 'cnt': 2, 'step': 2}, {'affixId': 3, 'cnt': 3, 'step': 2}, {'affixId': 4, 'cnt': 1, 'step': 1}, {'affixId': 10, 'cnt': 1, 'step': 2}], 'level': 14, 'mainAffixId': 1}, {'exp': 4130, 'type': 2, 'tid': 61012, 'subAffixList': [{'affixId': 1, 'cnt': 1, 'step': 1}, {'affixId': 5, 'cnt': 1, 'step': 2}, {'affixId': 6, 'cnt': 2, 'step': 1}, {'affixId': 7, 'cnt': 2, 'step': 3}], 'level': 11, 'mainAffixId': 1}, {'exp': 200, 'type': 3, 'tid': 55001, 'subAffixList': [{'affixId': 2, 'cnt': 1}, {'affixId': 5, 'cnt': 1, 'step': 2}, {'affixId': 8, 'cnt': 2, 'step': 2}, {'affixId': 10, 'cnt': 1}], 'level': 6, 'mainAffixId': 1}, {'type': 4, 'tid': 55002, 'subAffixList': [{'affixId': 1, 'cnt': 2, 'step': 3}, {'affixId': 3, 'cnt': 1, 'step': 2}, {'affixId': 6, 'cnt': 1, 'step': 1}, {'affixId': 11, 'cnt': 1}], 'level': 6, 'mainAffixId': 1}, {'type': 5, 'tid': 63025, 'subAffixList': [{'affixId': 2, 'cnt': 1, 'step': 2}, {'affixId': 5, 'cnt': 3, 'step': 2}, {'affixId': 11, 'cnt': 3, 'step': 5}, {'affixId': 12, 'cnt': 1, 'step': 2}], 'level': 15, 'mainAffixId': 1}, {'exp': 3580, 'type': 6, 'tid': 63026, 'subAffixList': [{'affixId': 1, 'cnt': 1, 'step': 1}, {'affixId': 5, 'cnt': 2, 'step': 2}, {'affixId': 11, 'cnt': 3, 'step': 5}, {'affixId': 12, 'cnt': 1, 'step': 1}], 'level': 13, 'mainAffixId': 3}], 'equipment': {'level': 70, 'tid': 21007, 'promotion': 5, 'rank': 1}, 'exp': 18082, 'level': 69}, 'level': 54, 'uid': 106031717}}, error: 'PlayerDetailInfo'
06-09 14:37:15 [INFO] nonebot_plugin_gocqhttp | [172822512] 发送好友 272962496(272962496)  的消息: [{"type":  ... (591747875)
06-09 14:37:15 [INFO] nonebot | Matcher(type='message', module=march7th.nonebot_plugin_srpanel) running complete

**Comment by mobyw** [comment]
1.1 版本面板 API 格式有修改，这几天会修复

**Comment by mobyw** [comment]
Fix in [140add](https://github.com/Mar-7th/March7th/commit/140add3e0f85ba3d83f17a41d69ccf91432d6d55)

**Comment by Xiaojack1026** [comment]
大佬好，更新指令是啥啊

**Comment by mobyw** [comment]
> 大佬好，更新指令是啥啊

目前还没有做直接通过 git 更新插件的指令，可以通过 git clone 仓库后手动 git pull 更新

更新索引文件使用 srupdate

更新遗器评分文件使用 srsupdate
