### ISSUE TITLE
[feature request] 抽卡记录查询

### ISSUE THREAD

**Issue by xxtg666** [Mar-7th/March7th#12]
扫码登录过的账户应该都可以获取到抽卡记录链接 可以做个像LittlePaimon那样的显示抽卡记录的功能么

**Comment by xxtg666** [comment]
也可以，用户用命令发记录的链接，然后根据uid存本地并且显示

**Comment by mobyw** [comment]
Add in [f67713c](https://github.com/Mar-7th/March7th/commit/f67713c0d1d4d709727caabfd946ed9a6ab663d8)
