### ISSUE TITLE
私聊图片在电脑端 QQNT 无法打开原图

### ISSUE THREAD

**Issue by Joseandluue** [Mar-7th/March7th#18]
查询角色攻略后，bot发出来的图片，在ntqq上无法打开，这是适配器的问题吗

**Comment by mobyw** [comment]
只有在 QQNT 上无法查看吗，旧的 QQ 是否可以查看

**Comment by mobyw** [comment]
可以先检查一下 `./data/nonebot_plugin_srres/guide` 文件夹对应的图片是否可以正常打开，如果是图片下载出错就删除对应图片文件，下次调用会自动重新下载

**Comment by Joseandluue** [comment]
图片在本地能正常打开，且只有ntqq无法打开，旧版本qq和手机qq能打开的
![image](https://github.com/Mar-7th/March7th/assets/55482264/08389b5f-73e9-4dba-8b88-c4b7b822f33c)
bot发出来的消息有显示缩略图

**Comment by Joseandluue** [comment]
> 图片在本地能正常打开，且只有ntqq无法打开，旧版本qq和手机qq能打开的（从ntqq上复制图片到聊天框也可以打开，另存为也可以打开）
 ![image](https://user-images.githubusercontent.com/55482264/268195680-08389b5f-73e9-4dba-8b88-c4b7b822f33c.png) bot发出来的消息有显示缩略图

**Comment by mobyw** [comment]
有试过群聊时 QQNT 是否可以正常显示吗

**Comment by Joseandluue** [comment]
不好意思，隔了这么久才回复你，刚刚我尝试了，群聊是没问题的可以打开，私聊就不行了

**Comment by mobyw** [comment]
如果是使用 go-cqhttp 作为客户端，请参考 Mrs4s/go-cqhttp/issues/2272

**Comment by mobyw** [comment]
go-cqhttp 已不建议作为新的部署的协议端使用，此 issue 将关闭
