### ISSUE TITLE
当前出现1034已无法通过米游社解决，米游社不会弹出验证码

### ISSUE THREAD

**Issue by mengluo04** [Mar-7th/March7th#21]
接口出现1034后打开米游社点击角色信息等不会和以前一样出现图片验证码进行验证，qpp上一切正常

**Comment by mobyw** [comment]
现在验证码似乎和设备 ID 与指纹绑定，可能需要添加过码配置，过几天写一下

**Comment by mengluo04** [comment]
> 现在验证码似乎和设备 ID 与指纹绑定，可能需要添加过码配置，过几天写一下

好的，非常感谢。我对这块属于完全不了解，不知道原理

**Comment by mobyw** [comment]
或者可以来 929275476 问
