### ISSUE TITLE
API返回1034

### ISSUE THREAD

**Issue by mengluo04** [Mar-7th/March7th#22]
1、调用`xxx/createVerification?is_high=false`获取到challenge和gt
2、使用极验第三代sdk创建验证码并完成验证
3、使用校验成功返回的参数：`geetest_challenge，geetest_seccode，geetest_validate`请求验证接口`xxx/verifyVerification`，接口返回`{'code': 200, 'msg': '操作成功', 'data': {'retcode': 0, 'message': 'OK', 'data': {'challenge': 'xxx'}}}`
4、调用深渊、角色等接口依旧返回1034

其他：
1、`xxx/createVerification?is_high=true`校验成功之后原神接口可以正常使用
2、群申请了没同意

**Comment by lulu666lulu** [comment]
按理来说，星铁的码用sdk应该过不去的

**Comment by lulu666lulu** [comment]
请检查协议实现是否有问题

**Comment by mengluo04** [comment]
> 按理来说，星铁的码用sdk应该过不去的

根据极验3的文档验证的，验证通过调用miHoYo的验证接口也返回成功
![image](https://github.com/Mar-7th/March7th/assets/32565940/baabb5cf-a4a5-43a5-b323-37cce26db00d)

**Comment by mengluo04** [comment]
> 请检查协议实现是否有问题

协议指的是？

**Comment by lulu666lulu** [comment]
星铁的geetest是定制的，如果你在外部使用时会报错的，你获取到的并不是星铁的验证码，所以让你检查协议实现

**Comment by mengluo04** [comment]
> 星铁的geetest是定制的，如果你在外部使用时会报错的，你获取到的并不是星铁的验证码，所以让你检查协议实现

好的，我再认真阅读代码，感谢回答

**Comment by mengluo04** [comment]
> 星铁的geetest是定制的，如果你在外部使用时会报错的，你获取到的并不是星铁的验证码，所以让你检查协议实现

能否提供这个接口的地址
![image](https://github.com/Mar-7th/March7th/assets/32565940/ce6a63fa-1951-4844-bc5f-c34b346bcaf2)

**Comment by lulu666lulu** [comment]
接口地址是一样的，参数有所区别

**Comment by lulu666lulu** [comment]
哦，这个
图片没加载出来（

**Comment by lulu666lulu** [comment]
请自行查找

**Comment by mobyw** [comment]
可以添加项目 README 中的 QQ 群

**Comment by mengluo04** [comment]
> 可以添加项目 README 中的 QQ 群

好，加了

**Comment by mobyw** [comment]
刚才粘贴错了，加现在的或者直接点链接加

**Comment by mengluo04** [comment]
> 刚才粘贴错了，加现在的或者直接点链接加

942679013  是这个吧，申请了

**Comment by mobyw** [comment]
QQ 群是回答正确问题自动通过的，检查一下你的 QQ 是不是被风控了

**Comment by mengluo04** [comment]
> QQ 群是回答正确问题自动通过的，检查一下你的 QQ 是不是被风控了

填了答案显示的等待群主通过，点进群聊天没反应，之前搞go-cqhttp好像是被风控过

**Comment by mengluo04** [comment]
> QQ 群是回答正确问题自动通过的，检查一下你的 QQ 是不是被风控了

![image](https://github.com/Mar-7th/March7th/assets/32565940/e514399f-9821-48b5-bf98-d75e851d47de)

**Comment by mobyw** [comment]
尝试使用新版本或手机 QQ 申请，这样的收不到验证消息

**Comment by mengluo04** [comment]
> 尝试使用新版本或手机 QQ 申请，这样的收不到验证消息

关了青少年模式重新申请了，收到拒绝的通知了，重新填了群组名申请

**Comment by mobyw** [comment]
没有直接进群就是没有申请成功，要不还是换号吧

**Comment by mengluo04** [comment]
> 尝试使用新版本或手机 QQ 申请，这样的收不到验证消息

手机申请可以了，加进来了
