### ISSUE TITLE
请更换nonebot_plugin_srres插件中的镜像源

### ISSUE THREAD

**Issue by QSlotus** [Mar-7th/March7th#29]
请更换nonebot_plugin_srres插件中的镜像源
ghproxy.com已失效

**Comment by QSlotus** [comment]
我自己改了一下但是报错了（悲

**Comment by QSlotus** [comment]
已解决，将config.py中的github_proxy置空并将https://mirror.ghproxy.com/加至下载链接之前即可

**Comment by mobyw** [comment]
在所使用的 `.env` 中添加

```dotenv
GITHUB_PROXY="..."
```

即可
