### ISSUE TITLE
导入抽卡记录失败

### ISSUE THREAD

**Issue by hiroshihuang** [Mar-7th/March7th#42]
### 在群里
![Clip_2024-04-12_03-18-53](https://github.com/Mar-7th/March7th/assets/164932517/3d97df6a-bc70-46cf-9933-b7607d674192)
![Clip_2024-04-12_03-19-25](https://github.com/Mar-7th/March7th/assets/164932517/76bb1f40-af78-45eb-bb13-de0095edc97e)
### 私聊
![Clip_2024-04-12_03-20-15](https://github.com/Mar-7th/March7th/assets/164932517/e88e02ac-f9ca-4378-b628-3f0181710088)

获取的抽卡链接应该没问题，我按照文档里的三个方法都试了，其他的都能更新，热佬们看看哪里有问题，先谢谢了

**Comment by mobyw** [comment]
更新失败是因为链接数据验证不通过，可以用现在的代码测试一下，有更多调试输出

私聊报错是因为 LLOneBot 无法处理私聊中带有@的消息，目前的代码已屏蔽私聊中的@

**Comment by hiroshihuang** [comment]
![Clip_2024-04-15_22-43-00](https://github.com/Mar-7th/March7th/assets/164932517/648d8b6f-78e3-45d2-861c-4eb72e553363)


> 更新失败是因为链接数据验证不通过，可以用现在的代码测试一下，有更多调试输出
> 
> 私聊报错是因为 LLOneBot 无法处理私聊中带有@的消息，目前的代码已屏蔽私聊中的@
测试是这样子

**Comment by mobyw** [comment]
图片里面的链接都是同一个，链接有效期只有 24 小时，已经过期了

**Comment by QSlotus** [comment]
请问问题解决了吗？我的也是这种问题：
私聊：
![image](https://github.com/Mar-7th/March7th/assets/109905194/29344a82-bb19-42b5-8092-af348708881e)
群聊：
![image](https://github.com/Mar-7th/March7th/assets/109905194/ea83b1b4-ef9a-41b4-87e3-b7b5a5283b40)
后端使用的是Lagrange，机器人代码使用的是最新的提交
刚用作者的机器人试了下是可以导入的，不知道我的是什么问题
请问大佬有什么解决方法吗

**Comment by mobyw** [comment]
Fixed in [126e9c7](https://github.com/Mar-7th/March7th/commit/126e9c7580384bb972d6874909b9e336d6b36423)
