### ISSUE TITLE
有办法热更新代码文件吗

### ISSUE THREAD

**Issue by QSlotus** [Mar-7th/March7th#43]
比如说在机器人运行的情况下更新插件代码，就不用每次重新部署了
不是更新资源，是更新机器人代码，比如说在最新的commit中修复了一个bug，然后我如何将这个commit的内容覆盖到原来的内容

**Comment by mobyw** [comment]
可以使用 `git` 管理，使用 `git clone` 仓库，更新时使用 `git pull`
