### ISSUE TITLE
使用srqr指令时无法正常发送图片进行绑定

### ISSUE THREAD

**Issue by HydraSu** [Mar-7th/March7th#47]
**环境**：
Docker下的Ubuntu 22.04
Python版本3.10.12
LLOneBot v3.23.0 + Onebot v11
**问题**：
发送srqr时日志有报错，无法正常发送二维码；根据教程发送srck+cookie后同样报错
能正常查询攻略
以下为报错
![March7th -1](https://github.com/Mar-7th/March7th/assets/96711662/5e73723a-1d0b-4e3f-8dd9-52bfa8654102)
![March7th -2](https://github.com/Mar-7th/March7th/assets/96711662/7bcb1a58-ee16-4a24-b092-1edeb4925d7a)
![March7th -3](https://github.com/Mar-7th/March7th/assets/96711662/8e95cda5-8222-4dbe-b8fa-daad4f666b55)

**Comment by mobyw** [comment]
协议端的报错，需要查看 LLOneBot 的调试日志

**Comment by mobyw** [comment]
是在私聊中使用的吗，LLOneBot 无法正常处理私聊中的 @ 操作

**Comment by HydraSu** [comment]
> 是在私聊中使用的吗，LLOneBot 无法正常处理私聊中的 @ 操作

是私聊中的

**Comment by mobyw** [comment]
测试一下现在的代码，应该是可用的

**Comment by HydraSu** [comment]
> 测试一下现在的代码，应该是可用的

已测试，私聊可用，辛苦了
