### ISSUE TITLE
sruid+uid无法正常绑定

### ISSUE THREAD

**Issue by maoxig** [Mar-7th/March7th#8]
抱歉这么晚打扰了。
使用指令`sruid`绑定uid时sql报错:`InterfaceError`,可能是https://github.com/Mar-7th/March7th/blob/3945f78d2763ff70419270e6b5fa1aa68b29a869/march7th/nonebot_plugin_srbind/__init__.py#L122-L133
125行之后的`uid`是否应该改成`sr_uid`?

**Comment by maoxig** [comment]
而且渠道服例如b服会以别的数字开头，122行匹配时要考虑这种情况不？还是说渠道服不支持这样绑定？

**Comment by mobyw** [comment]
> 使用指令`sruid`绑定uid时sql报错:`InterfaceError`,可能是https://github.com/Mar-7th/March7th/blob/3945f78d2763ff70419270e6b5fa1aa68b29a869/march7th/nonebot_plugin_srbind/__init__.py#L122-L133

这个有具体的绑定命令吗

**Comment by mobyw** [comment]
> 而且渠道服例如b服会以别的数字开头，122行匹配时要考虑这种情况不？还是说渠道服不支持这样绑定？

渠道服应该支持的，但是现在写的功能还没测试渠道服的，只在官中服做了测试，所以没往里面加，可以把 `[1]` 改成 `[15]` 试一下能不能用，现在 api 的这部分逻辑是按照原神的来写的。

**Comment by mobyw** [comment]
> 125行之后的`uid`是否应该改成`sr_uid`?

后面使用匹配的结果是为了避免不合法的 uid 插入数据表，但是现在的写法如果输了 10 位不会提示错误，而是会取前 9 位当作 uid 绑定，这个地方还要再改一下

**Comment by maoxig** [comment]
例如输入指令`sruid 1006281461`，算了我直接贴报错吧
![0F55BA8DB7FDD23504805F588DEE2171](https://github.com/Mar-7th/March7th/assets/123555887/bd421c12-b506-4ab1-8e29-b49bf8ac4e27)
![CC0180EE6B83A270ED3914669DE7A496](https://github.com/Mar-7th/March7th/assets/123555887/ecfad0d2-2a81-4bbb-8a25-271cfed09394)
![B5F9F645A3065A92F676FF12F4B34F3E](https://github.com/Mar-7th/March7th/assets/123555887/1053ab7e-4801-4242-be22-66770d5a6fb2)
似乎是因为https://github.com/Mar-7th/March7th/blob/3945f78d2763ff70419270e6b5fa1aa68b29a869/march7th/nonebot_plugin_srbind/models.py#L18
但是传入的参数是https://github.com/Mar-7th/March7th/blob/3945f78d2763ff70419270e6b5fa1aa68b29a869/march7th/nonebot_plugin_srbind/__init__.py#L122
(说实话我还没接触过sql，不过这里的参数应该有点问题吧，传了个`re.match`进去)
至于匹配的话，前面的if已经验证过了，我觉得这段应该改成这样
```python
        if not re.match(r"[1]\d{8}", sr_uid):
            msg = "SRUID格式错误"
        else:
            logger.info(f"开始为『{event.get_user_id()}』绑定SRUID『{sr_uid}』")
            user = UserBind(
                bot_id=bot.self_id,
                user_id=str(event.get_user_id()),
                sr_uid=sr_uid,
            )
            await set_user_srbind(user)
            msg = f"成功绑定SRUID『{sr_uid}』"
```
可能不太对，但是原来这个地方报错是肯定的

**Comment by maoxig** [comment]
> > 125行之后的`uid`是否应该改成`sr_uid`?
> 
> 后面使用匹配的结果是为了避免不合法的 uid 插入数据表，但是现在的写法如果输了 10 位不会提示错误，而是会取前 9 位当作 uid 绑定，这个地方还要再改一下

想要不匹配10位，正则表达式或许可以改成?
```python
uid = re.match(r"[1]\d{8}$", sr_uid)
```

**Comment by maoxig** [comment]
> > 125行之后的`uid`是否应该改成`sr_uid`?
> 
> 后面使用匹配的结果是为了避免不合法的 uid 插入数据表，但是现在的写法如果输了 10 位不会提示错误，而是会取前 9 位当作 uid 绑定，这个地方还要再改一下

`re.match()`的返回值是一个`re.Match`的对象，而不是匹配上的字符串，要取匹配上的字符串，要用别的方法来取。因此这里传入的参数和`UserBind`的`sr_uid`需要的似乎对不上

**Comment by mobyw** [comment]
> `re.match()`的返回值是一个`re.Match`的对象，而不是匹配上的字符串，要取匹配上的字符串，要用别的方法来取。因此这里传入的参数和`UserBind`的`sr_uid`需要的似乎对不上

这个确实有问题，马上修复一下

**Comment by mobyw** [comment]
修复了，可以测试下

**Comment by maoxig** [comment]
应该没问题了
