### ISSUE TITLE
错误代码1034

### ISSUE THREAD

**Issue by hooll** [Mar-7th/March7th#9]
使用srnote的时候，显示报错1034，重新将项目文件部署好并重新生成了数据库文件，还是有该报错

**Comment by mobyw** [comment]
1034是请求遇到验证码，需要手动在米游社角色界面过码或者修改密码重新扫码登录后使用

**Comment by hooll** [comment]
> 1034是请求遇到验证码，需要手动在米游社角色界面过码或者修改密码重新扫码登录后使用

更改米哈游账号的密码重新登录扫码就可以了吗？

**Comment by mobyw** [comment]
可以尝试一下，目前我自己的账号还没遇到过

**Comment by mobyw** [comment]
Fix in [52fa0d](https://github.com/Mar-7th/March7th/commit/52fa0dd6b9bfc71a380159605b8cc0bb45e6f93a)
